//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHIFA.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SHIFA.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All File Types (.*)|*.*.
        /// </summary>
        internal static string All_File_Type {
            get {
                return ResourceManager.GetString("All_File_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Engine is busying, wait for a while and try again..
        /// </summary>
        internal static string Backend_Busy {
            get {
                return ResourceManager.GetString("Backend_Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create RSA key pair at selected path.
        /// </summary>
        internal static string DialogTitle_CreateKey {
            get {
                return ResourceManager.GetString("DialogTitle_CreateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a file containing a key for decryption.
        /// </summary>
        internal static string DialogTitle_SelectKey {
            get {
                return ResourceManager.GetString("DialogTitle_SelectKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select manifest file path.
        /// </summary>
        internal static string DialogTitle_SelectManifest {
            get {
                return ResourceManager.GetString("DialogTitle_SelectManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a pem for converting to xml format.
        /// </summary>
        internal static string DialogTitle_SelectPem {
            get {
                return ResourceManager.GetString("DialogTitle_SelectPem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a file to be encrypted.
        /// </summary>
        internal static string DialogTitle_SelectPlain {
            get {
                return ResourceManager.GetString("DialogTitle_SelectPlain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a xml file containing a public key.
        /// </summary>
        internal static string DialogTitle_SelectPublicKey {
            get {
                return ResourceManager.GetString("DialogTitle_SelectPublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to convert to private key.
        /// </summary>
        internal static string Error_convertToPrivateKey {
            get {
                return ResourceManager.GetString("Error_convertToPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to convert to public key.
        /// </summary>
        internal static string Error_convertToPublicKey {
            get {
                return ResourceManager.GetString("Error_convertToPublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Must specify a public key for encryption!.
        /// </summary>
        internal static string Error_Need_PublicKey {
            get {
                return ResourceManager.GetString("Error_Need_PublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Decryption is done, file is saved at {0}.
        /// </summary>
        internal static string Out_msg_decryption_success {
            get {
                return ResourceManager.GetString("Out_msg_decryption_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Encryption is done, key information:.
        /// </summary>
        internal static string Out_msg_encrypt_success {
            get {
                return ResourceManager.GetString("Out_msg_encrypt_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Decrypting....
        /// </summary>
        internal static string Out_msg_start_decryption {
            get {
                return ResourceManager.GetString("Out_msg_start_decryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Encrypting....
        /// </summary>
        internal static string Out_msg_start_encryption {
            get {
                return ResourceManager.GetString("Out_msg_start_encryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Imported public key:.
        /// </summary>
        internal static string Output_msg_importKey {
            get {
                return ResourceManager.GetString("Output_msg_importKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pem files(.pem)|*.pem.
        /// </summary>
        internal static string PEM_File_Type {
            get {
                return ResourceManager.GetString("PEM_File_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Now compressing....
        /// </summary>
        internal static string Start_Compression {
            get {
                return ResourceManager.GetString("Start_Compression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Xml files (.xml)|*.xml.
        /// </summary>
        internal static string XML_File_Type {
            get {
                return ResourceManager.GetString("XML_File_Type", resourceCulture);
            }
        }
    }
}
